language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - redis-server
# command to install dependencies
install:
  - pip install tox-travis
  - python setup.py install
# command to run tests
script: 
  - tox